apiVersion: v1
kind: Service
metadata:
    name: "aksdevopsstartercluster-b288"
    labels:
        app: "aksdevopsstartercluster-b288"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksdevopsstartercluster-b288"