on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksdevopsstarteracr.azurecr.io
        username: ${{ secrets.acr_aksdevopsstarteracr_username }}
        password: ${{ secrets.acr_aksdevopsstarteracr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/GroceryListHelper" -f  "GroceryListHelper/Server/Dockerfile" -t aksdevopsstarteracr.azurecr.io/aksdevopsstartercluster:${{ github.sha }} --label dockerfile-path=GroceryListHelper/Server/Dockerfile
        docker push aksdevopsstarteracr.azurecr.io/aksdevopsstartercluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdevopsstartercluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksdevopsstartercluster9830 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksdevopsstartercluster9830`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksdevopsstartercluster9830
        container-registry-url: aksdevopsstarteracr.azurecr.io
        container-registry-username: ${{ secrets.acr_aksdevopsstarteracr_username }}
        container-registry-password: ${{ secrets.acr_aksdevopsstarteracr_password }}
        secret-name: aksdevopsstadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksdevopsstartercluster9830
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksdevopsstarteracr.azurecr.io/aksdevopsstartercluster:${{ github.sha }}
        imagepullsecrets: |
          aksdevopsstadockerauth
